import "./globals.css";
import { chillax, satoshi, gambetta } from "@/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${chillax.variable} ${satoshi.variable} ${gambetta.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
